alias projects='cd ~/Projects'
alias tnotes='projects && cd technical-notes'
alias pnotes='projects && cd personal-notes'
alias dotfiles='projects && cd dotfiles'
alias wttr='curl wttr.in'
alias zen='projects && cd zenlytic'
alias zenf='projects && cd zenlytic/services/front_end'
