alias projects='cd ~/Projects'
alias dotfiles='projects && cd dotfiles'
alias vdotfiles='vim ~/Projects/dotfiles'
alias vlimsux='vim ~/Projects/lims-ux'
alias vlimsservice='vim ~/Projects/lims-service'
alias limsux='cd ~/Projects/lims-ux'
alias limsservice='cd ~/Projects/lims-service'
