alias ahk='code ~/external/work_hot_key_scripts.ahk'
alias external='cd ~/external'
alias dotfiles='external && cd dotfiles'
alias projects='cd ~/../../Projects'
alias trs='projects && cd TRS'
alias trssite='trs && cd TRSIII.Site'